const studioNames = ['Music Boutique',
'Music Crew',
'Unique Music',
'Vanomic',
'Funky Hearts',
'Spunky Beans',
'Bored Brothers',
'Lucent House',
'Spectral Dreams',
'Lumasonic',
'Tellular',
'Virtuaris',
'Onetimee',
'Dash Genius',
'Activity Bag',
'Pheale',
'Saxene',
'MixPods',
'Superb Story',
'Click Concert',
'Dexonic',
'Orgasmist',
'Crimson Royale',
'Freelyng',
'Bumbaloo',
'Stomp Around',
'MrktKng',
'Hardcore Hero',
'StreamZing',
'SmashVibe',
'MentalMist',
'Play Fairy',
'PopStax',
'DABMO',
'SYNZU',
'City Mingles',
'UberPlayer',
'Sound Bowl',
'HipTUBE',
'Altarcade',
'Sunset Gem',
'RapBack',
'Gecko Country',
'Seratina',
'Leisure Fox',
'OPEN SHOW',
'Nukito',
'Night Sugar',
'Magictutor',
'PALADIR',
'Bodoko',
'Disco Monster',
'Factory Merch',
'Trinola',
'MonkeyUncle',
'PINKTWIGS',
'Zadoa',
'BuffalloSaloon',
'Edittime',
'Legal Devil',
'TenPipes',
'Sound Instinct',
'Pay 4 Performance',
'Voicewave',
'Rap Saavy',
'Rival Icon',
'KIP PROPHET',
'FunkyDrum',
'Storm Fever',
'Soundeca',
'First Rehearsal',
'Valiant City',
'Sonic Mantra',
'Podtrax',
'Attuna',
'VOLOXY',
'Kyopi',
'EverGenie',
'SonicSwan',
'AtomBoom',
'Vivaphonic',
'MEGASHRED',
'Ampeur',
'Cocktail Circuit',
'Cymbalis',
'Grunge Logic',
'Onyx Angel',
'Third Wish',
'Afternoon News',
'Jackpot Saloon',
'GoofyGoose',
'Shookk',
'Story Fellas',
'IvyTap',
'Rebellogic',
'Sonabar',
'Sirensa',
'HawtDogz',
'Vobz',
'Rumble Crew'];

module.exports.studioNames = studioNames;